import Link from "next/link";
import {ArrowRight,Check,ShieldCheck} from "lucide-react";
import {AnimatedPlant,Reveal} from "@/components/motion";
import {HomeFAQ,HomeTools,PhaseChooser} from "@/components/home-sections";
import {phases} from "@/lib/content";

export default function HomePage(){return <>
<section className="container-page grid min-h-[calc(100vh-4rem)] items-center gap-10 py-12 lg:grid-cols-[1.08fr_.92fr]"><Reveal><div><h1 className="max-w-3xl font-serif text-5xl font-semibold leading-[.98] sm:text-7xl"><span className="mb-3 block font-sans text-[.42em] font-extrabold uppercase tracking-[.12em] text-forest">Cannabis anbauen</span>Vom Samen<br/><span className="text-moss">bis zur Ernte.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-forest/75">Verstehe jede Phase, behalte Klima und Aufgaben im Blick und dokumentiere deinen legalen privaten Eigenanbau – ohne Konto und ohne Datenupload.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="inline-flex min-h-12 items-center gap-2 rounded-full bg-forest px-6 font-bold text-cream shadow-md transition hover:-translate-y-0.5 hover:bg-moss hover:shadow-lg" href="/werkzeuge/grow-planer">Anbau starten <ArrowRight className="size-4"/></Link><Link className="inline-flex min-h-12 items-center rounded-full border-2 border-moss/35 bg-white/60 px-6 font-bold transition hover:border-moss hover:bg-white" href="/anbauphasen">Phasen entdecken</Link></div><p className="mt-6 flex items-center gap-2 text-xs font-semibold text-forest/60"><ShieldCheck className="size-4 text-moss"/>Ausschließlich für volljährige Nutzer und legalen privaten Eigenanbau.</p></div></Reveal><Reveal><AnimatedPlant/></Reveal></section>
<section className="container-page py-16"><Reveal><p className="eyebrow">Der Lebenszyklus</p><div className="mt-4 flex items-end justify-between gap-4"><h2 className="font-serif text-4xl font-bold sm:text-5xl">Zehn Phasen.<br/>Ein klarer Weg.</h2><Link className="hidden items-center gap-2 font-bold sm:flex" href="/anbauphasen">Alle Phasen <ArrowRight className="size-4"/></Link></div><div className="mt-10 flex snap-x gap-4 overflow-x-auto pb-5">{phases.map((p,i)=><Link key={p.slug} href={`/anbauphasen/${p.slug}`} className="card min-w-[250px] snap-start p-5"><span className="grid size-10 place-items-center rounded-full bg-sage/20 font-serif font-bold">{i+1}</span><h3 className="mt-8 text-lg font-bold">{p.title}</h3><p className="mt-2 text-sm text-forest/60">{p.duration}</p></Link>)}</div></Reveal></section>
<section className="bg-gradient-to-br from-forest via-[#15513f] to-moss py-20 text-cream shadow-[inset_0_1px_rgba(255,255,255,.08)]"><div className="container-page"><Reveal><p className="eyebrow !text-[#b8d8ae]">Werkzeuge, die mitdenken</p><h2 className="mt-4 max-w-2xl font-serif text-4xl font-bold sm:text-5xl">Weniger raten. Besser beobachten.</h2><div className="mt-10 text-forest"><HomeTools/></div></Reveal></div></section>
<section className="container-page py-20"><Reveal><p className="eyebrow">Situativ statt pauschal</p><h2 className="mt-4 font-serif text-4xl font-bold sm:text-5xl">Was braucht deine Pflanze gerade?</h2><div className="mt-8"><PhaseChooser/></div></Reveal></section>
<section className="container-page grid gap-5 py-12 lg:grid-cols-2"><Reveal className="card p-7 sm:p-10"><p className="eyebrow">Indoor & Outdoor</p><h2 className="mt-4 font-serif text-3xl font-bold">Kontrolle oder Natur?</h2><p className="mt-4 leading-7 text-forest/70">Indoor bietet steuerbare Bedingungen, braucht aber Technik und sichere Elektrik. Outdoor nutzt Sonne und natürliche Zyklen, ist dafür stärker von Wetter, Saison und Standort abhängig.</p><Link href="/wissen/indoor-oder-outdoor" className="mt-6 inline-flex items-center gap-2 font-bold">Vergleich lesen <ArrowRight className="size-4"/></Link></Reveal><Reveal className="card bg-sage/15 p-7 sm:p-10"><p className="eyebrow">Anfängerfehler</p><h2 className="mt-4 font-serif text-3xl font-bold">Mehr ist selten besser.</h2><ul className="mt-5 space-y-3">{["Gießen nach Kalender statt Topfgewicht","Mehrere Parameter gleichzeitig ändern","Einzelne Symptome vorschnell deuten","Reife nur nach der Wochenzahl beurteilen"].map(x=><li key={x} className="flex gap-3"><Check className="mt-0.5 size-5 shrink-0 text-moss"/>{x}</li>)}</ul></Reveal></section>
<section className="container-page py-20"><div className="grid gap-8 lg:grid-cols-[1fr_.85fr]"><Reveal><p className="eyebrow">Persönlich & lokal</p><h2 className="mt-4 font-serif text-4xl font-bold sm:text-5xl">Dein Grow.<br/>Deine Beobachtungen.</h2><p className="mt-5 max-w-xl leading-7 text-forest/70">Erstelle eine Zeitleiste, protokolliere Klima, Gießen und Notizen. Alles bleibt in deinem Browser und kann jederzeit exportiert werden.</p><Link href="/mein-grow" className="mt-7 inline-flex min-h-12 items-center gap-2 rounded-full bg-forest px-6 font-bold text-cream">Grow-Tagebuch öffnen <ArrowRight className="size-4"/></Link></Reveal><Reveal className="card p-7"><p className="eyebrow">Häufig gefragt</p><HomeFAQ/></Reveal></div></section>
</>}
