"use client";
import {useState} from "react";
import Link from "next/link";
import {ArrowRight,Check,Search} from "lucide-react";
import {knowledge,phases,problems} from "@/lib/content";
import {cn} from "@/lib/utils";
export function PhaseGrid(){return <div className="grid gap-4 md:grid-cols-2">{phases.map((p,i)=><Link className="card group grid grid-cols-[auto_1fr_auto] items-center gap-4 p-5 transition hover:-translate-y-1" href={`/anbauphasen/${p.slug}`} key={p.slug}><span className="grid size-12 place-items-center rounded-2xl bg-sage/15 font-serif text-lg font-bold">{i+1}</span><span><b className="text-lg">{p.title}</b><span className="mt-1 block text-sm text-forest/60">{p.duration}</span></span><ArrowRight className="size-5 transition group-hover:translate-x-1"/></Link>)}</div>}
export function Checklist({items,storageKey}:{items:string[];storageKey:string}){const[done,setDone]=useState<number[]>(()=>[]);const toggle=(i:number)=>{const next=done.includes(i)?done.filter(x=>x!==i):[...done,i];setDone(next);localStorage.setItem(`check_${storageKey}`,JSON.stringify(next))};return <div><div className="mb-5 flex items-center justify-between text-sm"><b>{done.length} von {items.length} erledigt</b><span>{Math.round(done.length/items.length*100)} %</span></div><div className="h-2 overflow-hidden rounded-full bg-sage/20"><div className="h-full bg-amber transition-all" style={{width:`${done.length/items.length*100}%`}}/></div><div className="mt-5 grid gap-2">{items.map((x,i)=><button onClick={()=>toggle(i)} key={x} className="flex min-h-12 items-center gap-3 rounded-xl border border-forest/10 bg-white p-3 text-left"><span className={cn("grid size-6 shrink-0 place-items-center rounded-full border",done.includes(i)&&"border-moss bg-moss text-white")}>{done.includes(i)&&<Check className="size-4"/>}</span><span className={cn(done.includes(i)&&"line-through opacity-60")}>{x}</span></button>)}</div></div>}
export function ProblemGrid(){return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{problems.map(p=><Link href={`/probleme/${p.slug}`} key={p.slug} className="card p-5 transition hover:-translate-y-1"><span className={cn("rounded-full px-3 py-1 text-xs font-bold",p.urgency==="sofort"||p.urgency==="hoch"?"bg-amber/20":"bg-sage/20")}>Dringlichkeit: {p.urgency}</span><h2 className="mt-5 text-xl font-bold">{p.title}</h2><p className="mt-2 text-sm leading-6 text-forest/65">{p.symptoms}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold">Prüfschritte <ArrowRight className="size-4"/></span></Link>)}</div>}
export function KnowledgeGrid(){const[q,setQ]=useState("");const[topic,setTopic]=useState("Alle");const topics=["Alle",...new Set(knowledge.map(x=>x.topic))];const items=knowledge.filter(x=>(topic==="Alle"||x.topic===topic)&&`${x.title} ${x.excerpt}`.toLowerCase().includes(q.toLowerCase()));return <><div className="card grid gap-3 p-4 sm:grid-cols-[1fr_auto]"><label className="relative"><Search className="absolute left-4 top-3.5 size-5 text-forest/40"/><span className="sr-only">Wissen durchsuchen</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Wissen durchsuchen …" className="min-h-12 w-full rounded-xl border border-forest/15 bg-white pl-12 pr-4"/></label><div className="flex gap-2 overflow-x-auto">{topics.map(x=><button className={cn("min-h-12 whitespace-nowrap rounded-full px-4 text-sm font-bold",topic===x?"bg-forest text-cream":"bg-sage/10")} onClick={()=>setTopic(x)} key={x}>{x}</button>)}</div></div><p className="my-5 text-sm text-forest/60">{items.length} Beiträge gefunden</p><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(x=><Link href={`/wissen/${x.slug}`} className="card p-6 transition hover:-translate-y-1" key={x.slug}><span className="eyebrow">{x.topic} · {x.phase}</span><h2 className="mt-5 text-xl font-bold">{x.title}</h2><p className="mt-3 text-sm leading-6 text-forest/65">{x.excerpt}</p><ArrowRight className="mt-7 size-5"/></Link>)}</div></>}
