"use client";
import * as Accordion from "@radix-ui/react-accordion";
import {ChevronDown,Info,TriangleAlert} from "lucide-react";
import {cn} from "@/lib/utils";
import type {ButtonHTMLAttributes,InputHTMLAttributes,SelectHTMLAttributes,TextareaHTMLAttributes,ReactNode} from "react";

export function Button({className,...props}:ButtonHTMLAttributes<HTMLButtonElement>){return <button className={cn("inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-forest px-5 py-2.5 text-sm font-bold text-cream shadow-sm transition hover:-translate-y-0.5 hover:bg-moss hover:shadow-md disabled:cursor-not-allowed disabled:opacity-50",className)} {...props}/>}
export function Input({className,...props}:InputHTMLAttributes<HTMLInputElement>){return <input className={cn("min-h-12 w-full rounded-xl border border-forest/20 bg-white px-4 text-forest placeholder:text-forest/40",className)} {...props}/>}
export function Select({className,children,...props}:SelectHTMLAttributes<HTMLSelectElement>){return <select className={cn("min-h-12 w-full rounded-xl border border-forest/20 bg-white px-4 text-forest",className)} {...props}>{children}</select>}
export function Textarea({className,...props}:TextareaHTMLAttributes<HTMLTextAreaElement>){return <textarea className={cn("min-h-28 w-full rounded-xl border border-forest/20 bg-white p-4 text-forest",className)} {...props}/>}
export function Field({label,hint,children}: {label:string;hint?:string;children:ReactNode}){return <label className="grid gap-2 text-sm font-bold text-forest"><span>{label}</span>{children}{hint&&<span className="text-xs font-normal text-forest/60">{hint}</span>}</label>}
export function Notice({children,warning=false}: {children:ReactNode;warning?:boolean}){const Icon=warning?TriangleAlert:Info;return <div className={cn("flex gap-3 rounded-2xl border p-4 text-sm leading-6",warning?"border-amber/45 bg-amber/15":"border-moss/30 bg-sage/20")}><Icon className={cn("mt-0.5 size-5 shrink-0",warning?"text-earth":"text-moss")} aria-hidden/ ><div>{children}</div></div>}
export function Badge({children}: {children:ReactNode}){return <span className="inline-flex rounded-full border border-moss/15 bg-sage/25 px-3 py-1 text-xs font-bold text-forest">{children}</span>}
export function FAQ({items}:{items:{q:string;a:string}[]}){return <Accordion.Root type="single" collapsible className="divide-y divide-forest/10">{items.map((x,i)=><Accordion.Item value={String(i)} key={x.q}><Accordion.Header><Accordion.Trigger className="group flex w-full items-center justify-between gap-4 py-5 text-left font-bold"><span>{x.q}</span><ChevronDown className="size-5 transition group-data-[state=open]:rotate-180"/></Accordion.Trigger></Accordion.Header><Accordion.Content className="pb-5 leading-7 text-forest/70">{x.a}</Accordion.Content></Accordion.Item>)}</Accordion.Root>}
