export const STORAGE_KEY="grownavi_grows_v1";
export const LEGACY_STORAGE_KEY="gruenspur_grows_v1";
export type ClimateEntry={date:string;temperature:number;humidity:number};
export type JournalEntry={id:string;date:string;note:string;kind:"Notiz"|"Gießen"|"Düngung"|"Phase"};
export type GrowProject={id:string;demo?:boolean;name:string;genetics:string;startDate:string;setting:"Indoor"|"Outdoor";phase:number;harvestDate?:string;climate:ClimateEntry[];entries:JournalEntry[];tasks:{id:string;text:string;done:boolean}[]};
export const demoProject:GrowProject={id:"demo-grow",demo:true,name:"Beispiel: Waldlicht",genetics:"Demo-Hybrid (Beispieldaten)",startDate:"2026-05-03",setting:"Indoor",phase:5,climate:[{date:"2026-05-10",temperature:24,humidity:69},{date:"2026-05-17",temperature:25,humidity:65},{date:"2026-05-24",temperature:25,humidity:61},{date:"2026-06-01",temperature:24,humidity:57},{date:"2026-06-08",temperature:23,humidity:53},{date:"2026-06-15",temperature:24,humidity:50}],entries:[{id:"d1",date:"2026-05-03",kind:"Phase",note:"Keimung gestartet; sauberes Werkzeug vorbereitet."},{id:"d2",date:"2026-05-18",kind:"Gießen",note:"Topf deutlich leichter, langsam und gleichmäßig gegossen."},{id:"d3",date:"2026-05-27",kind:"Notiz",note:"Kompaktes Wachstum, neue Triebe wirken gesund."},{id:"d4",date:"2026-06-10",kind:"Phase",note:"Übergang zur Blüte dokumentiert."},{id:"d5",date:"2026-06-16",kind:"Düngung",note:"Zurückhaltende Blütennahrung, Reaktion beobachten."}],tasks:[{id:"t1",text:"Blattunterseiten kontrollieren",done:true},{id:"t2",text:"Nachtfeuchte protokollieren",done:false},{id:"t3",text:"Schwere Triebe prüfen",done:false}]};
export function loadProjects(storage:Pick<Storage,"getItem">=localStorage):GrowProject[]{try{const raw=storage.getItem(STORAGE_KEY)??storage.getItem(LEGACY_STORAGE_KEY);return raw?JSON.parse(raw):[demoProject]}catch{return[demoProject]}}
export function saveProjects(data:GrowProject[],storage:Pick<Storage,"setItem">=localStorage){storage.setItem(STORAGE_KEY,JSON.stringify(data))}
export function exportProjects(data:GrowProject[]){return JSON.stringify({schemaVersion:1,exportedAt:new Date().toISOString(),projects:data},null,2)}
export function importProjects(raw:string):GrowProject[]{const parsed:unknown=JSON.parse(raw);if(!parsed||typeof parsed!=="object"||!("schemaVersion" in parsed)||!("projects" in parsed)||!Array.isArray(parsed.projects))throw new Error("Die Datei ist kein gültiger GROWNAVI-Export.");for(const p of parsed.projects){if(!p||typeof p.name!=="string"||!Array.isArray(p.entries)||!Array.isArray(p.climate))throw new Error("Mindestens ein Projekt ist unvollständig.")}return parsed.projects as GrowProject[]}
