// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/anbauphasen/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/anbauphasen/[slug]">> = Specific
  const handler = {} as typeof import("../../app/anbauphasen/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/anbauphasen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/anbauphasen">> = Specific
  const handler = {} as typeof import("../../app/anbauphasen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/datenschutz/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/datenschutz">> = Specific
  const handler = {} as typeof import("../../app/datenschutz/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../app/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/grundlagen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/grundlagen">> = Specific
  const handler = {} as typeof import("../../app/grundlagen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mein-grow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mein-grow">> = Specific
  const handler = {} as typeof import("../../app/mein-grow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/probleme/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/probleme/[slug]">> = Specific
  const handler = {} as typeof import("../../app/probleme/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/probleme/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/probleme">> = Specific
  const handler = {} as typeof import("../../app/probleme/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/rechtliches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rechtliches">> = Specific
  const handler = {} as typeof import("../../app/rechtliches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sortenkunde/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sortenkunde">> = Specific
  const handler = {} as typeof import("../../app/sortenkunde/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/werkzeuge/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/werkzeuge/[slug]">> = Specific
  const handler = {} as typeof import("../../app/werkzeuge/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/werkzeuge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/werkzeuge">> = Specific
  const handler = {} as typeof import("../../app/werkzeuge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/wissen/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wissen/[slug]">> = Specific
  const handler = {} as typeof import("../../app/wissen/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/wissen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wissen">> = Specific
  const handler = {} as typeof import("../../app/wissen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
